# Ansible pipeline
# Tesing

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: UsePythonVersion@0
  displayName: 'Install Python'
  inputs:
    versionSpec: '3.10.13'

- task: AzureCLI@2
  displayName: 'Azure CLI'
  inputs:
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      #echo "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID]$(az account show --query="id" -o tsv)"
      #echo "##vso[task.setvariable variable=ARM_CLIENT_ID]${servicePrincipalId}"
      #echo "##vso[task.setvariable variable=ARM_CLIENT_SECRET]${servicePrincipalKey}"
      #echo "##vso[task.setvariable variable=ARM_TENANT_ID]${tenantId}"

- script: pip install ansible
  displayName: 'Install Ansible'

- script: pip install -r https://raw.githubusercontent.com/ansible-collections/azure/dev/requirements-azure.txt
  displayName: 'Install Azure modules needed'

- script: ansible-galaxy collection install azure.azcollection
  displayName: 'Install Ansible Azure Collection'
  
- script: ansible-playbook -i inv site.yml
  displayName: 'Run Ansible Playbook'
  env:
    AZURE_CLIENT_ID: 769cabdb-a4d5-4199-a760-b72ca471f16d
    AZURE_SECRET: E~w8Q~NQCn12IR0e_.hCtaV2fNI9quwW8oT5maks
    AZURE_SUBSCRIPTION_ID: e9a82d9b-fa70-49d3-a021-f33cad90e629
    AZURE_TENANT: 938cd77c-7886-4bb2-bab2-9726d7cff02e
      
